### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by tut-byl-ya** [AltronMaxX/FNF-AltronixEngine#10]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 11 pro max 64x

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.5 dev 

## Please describe your issue. Provide extensive detail and images if possible.
https://cdn.discordapp.com/attachments/916627367353524246/1046830315429167234/image.png
lol
1.заходим во фри плей
2.нажимаем на пробел
3.еще раз нажимаем на пробел 
4.листаем сложности
5.получаем невидимую сложность
вот гайд на получение самой крутой сложности в игре, спасибо за внимание
English:
1. go to the freeplay
2. press the space bar
3. press the space bar again
4. flipping through the difficulties
5. we get invisible difficulty
here is a guide for getting the coolest difficulty in the game, thank you for your attention

**Comment by AltronMaxX** [comment]
Забавный факт - у меня баг не срабатывает

**Comment by tut-byl-ya** [comment]
хммм

**Comment by tut-byl-ya** [comment]
сейчас проверю

**Comment by tut-byl-ya** [comment]
хуй занет у меня тоже перестало работать
